# SIMPLE_WAYOUT with Official Greenfield Image
# This uses the official Greenfield Dockerfile from the repository

version: '3.8'

services:
  # Official Greenfield compositor-proxy (built from source)
  compositor-proxy:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: compositor-proxy-official
    command: >
      --bind-port 8081
      --bind-ip 0.0.0.0
      --allow-origin '*'
      --encoder x264
    ports:
      - "8081:8081"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      - HOST=compositor-proxy-official
      - XAUTHORITY=/tmp/.Xauthority
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "-f", "node"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # SIMPLE_WAYOUT application
  simple-wayout:
    build:
      context: .
      dockerfile: Dockerfile
    image: simple-wayout:latest
    container_name: simple-wayout
    depends_on:
      compositor-proxy:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - COMPOSITOR_URL=ws://compositor-proxy:8081
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
